apiVersion: v1
kind: Pod
metadata:
  name: gh-service-monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8083'
spec:
  containers:
  - name: monitor
    image: docker.io/galsolom/ghmonitor:0.1
    ports:
    - containerPort: 8083
    env:
      - name: GH_STATUSURL
        value: https://www.githubstatus.com/api/v2/components.json
      - name: GH_MONITORED
        value: "API Requests,Codespaces,GitHub Packages"